name: go test
on: [push]
jobs:
    sdk-go-lint:
        runs-on: ubuntu-latest
        steps:
            - name: git clone
              uses: actions/checkout@v4

            - name: set up go
              uses: actions/setup-go@v5
              with:
                  go-version: 1.21.1

            - name: go test
              run: go test ./...
