name: wheels

on:
  # push:
  workflow_dispatch:
    inputs:
      VERSION:
        description: "The version to release"
        required: true

env:
  PYTHON_VERSION: 3.12
  GO_VERSION: 1.22.0

jobs:
  build_sdist:
    name: sdist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build sdist
        run: pipx run build --sdist

      - name: Check metadata
        run: pipx run twine check dist/*

      - uses: actions/upload-artifact@v4
        with:
          name: wheels-artifacts-sdist
          path: dist/*.tar.gz

  build_wheels:
    name: ${{ matrix.platform }}
    runs-on: ${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: ubuntu-latest
            platform: linux
          - image: macos-13
            platform: macos-amd64
          - image: macos-14
            platform: macos-arm64
          - image: windows-latest
            platform: windows

    steps:
      - name: git clone ${{ github.ref_name }}
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: set up go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Set up QEMU
        if: matrix.platform == 'linux'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Build wheels
        if: matrix.platform != 'macos-arm64'
        uses: pypa/cibuildwheel@v2.21.3
        env:
          MACOSX_DEPLOYMENT_TARGET: 13.0

      - name: Build wheels
        if: matrix.platform == 'macos-arm64'
        uses: pypa/cibuildwheel@v2.21.3
        env:
          # TODO: default wheel repair does not recognize the arm64 wheel.
          # This seems like a bug in delocate-wheel, which is the tool used by cibuildwheel,
          # since the binary works fine when installed. However, we skip a more thorough
          # investigation for now and just disable the repair step.
          CIBW_REPAIR_WHEEL_COMMAND: ""
          MACOSX_DEPLOYMENT_TARGET: 14.0

      - name: Verify clean directory
        run: git diff --exit-code
        shell: bash

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-artifacts-${{ matrix.platform }}
          path: wheelhouse/*.whl

  upload:
    name: upload
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-python@v5

      - uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: dist

      # TODO: Add a step to upload to PyPI
